### ISSUE TITLE
Constructor in Enums

### ISSUE THREAD

**Issue by parkito** [RuslAys/mobile-operator#2]
https://github.com/RuslAys/mobile-operator/blob/5a7459ff1fa3339b22c600fc4bbab74c3fe9c154/src/main/java/ru/javaschool/mobileoperator/domain/enums/UserRoleEnum.java#L8

For what?

**Comment by RuslAys** [comment]
For nothing. I`ve deleted it.

**Comment by parkito** [comment]
Close issue then
